version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
      - /etc/localtime:/etc/localtime:ro  # 시간 동기화
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aibayo
      - MONGO_INITDB_ROOT_PASSWORD=aibayo

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    volumes:
      - /etc/localtime:/etc/localtime:ro  # 시간 동기화
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=aibayo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=aibayo
      - ME_CONFIG_MONGODB_SERVER=mongodb

  mysql:
    image: mysql  # 최신 버전을 사용하기 위해 태그를 생략함
    container_name: mysql_db
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro  # 시간 동기화
    environment:
      - MYSQL_ROOT_PASSWORD=aibayo
      - MYSQL_DATABASE=aicoMySQL
      - MYSQL_USER=aico
      - MYSQL_PASSWORD=aico1234!

volumes:
  mongo: {}
  mysql: {}
