version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aibayo
      - MONGO_INITDB_ROOT_PASSWORD=aibayo

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=aibayo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=aibayo
      - ME_CONFIG_MONGODB_SERVER=mongodb

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=aibayo
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword

volumes:
  mongo: {}
  mysql: {}
